### ISSUE TITLE
Get-PsIntuneDevice does not pull memory data

### ISSUE THREAD

**Issue by MattPennerVVUSD** [Skatterbrainz/psIntune#5]
When running $devices = Get-PsIntuneDevice -UserName $username -DeviceOS Windows -Detail Detailed -ShowProgress $True on our tenant I retrieve 3,798 devices with all the relevant info.  However, the MemoryGB field reports 0 for all records.  I have confirmed in the Intune portal that all devices are correctly reporting memory to Intune.

Using psIntune 0.1.16

**Comment by MattPennerVVUSD** [comment]
Hmmm, this seems to be a known issue.  This might be a problem with the MS Graph API.

https://techcommunity.microsoft.com/t5/microsoft-intune/total-physical-memory-attribute-graph-location/m-p/2108126

**Comment by Skatterbrainz** [comment]
I'm way behind on issue comments/follow-up - sorry.  yes, it looks like there's some gaps in the Graph dataset. i've been told improvements are on the way, but not sure when.
